---
- name: This is my first ever webserver playbook
  hosts: jansible_gitclient

  tasks:
    - name: Package installation
      yum: name=httpd state=present

    - name: Amending webserver configuration file
      copy: dest=/var/www/html/index.html content="This is my first ever webserver playbook with Jenkins automation, continueous deployment. More to come, stay tuned."

    - name: Starting webserver services
      service: name=httpd state=started

...
